package cn.sduonline.wings.model.condition;

import java.io.Serializable;

import lombok.Data;

/**
 * Created by imaxct on 18-9-29.
 */
@Data
public class SelectCondition implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_select.student_id
	 *
	 * @mbg.generated Sat Sep 29 20:10:15 CST 2018
	 */
	private Long studentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_select.course_id
	 *
	 * @mbg.generated Sat Sep 29 20:10:15 CST 2018
	 */
	private Long courseId;

}
