package cn.sduonline.wings.model.condition;

import java.io.Serializable;

import lombok.Data;

/**
 * Created by imaxct on 18-9-29.
 */
@Data
public class SettingCondition implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_setting.setting_name
	 *
	 * @mbg.generated Sat Sep 29 20:10:15 CST 2018
	 */
	private String settingName;
}
