package cn.sduonline.wings.model.condition;

import java.io.Serializable;

import lombok.Data;

/**
 * Created by imaxct on 18-9-29.
 */
@Data
public class StudentCondition implements Serializable {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_student.student_no
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String studentNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_student.student_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.id_no
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_student.academy
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String academy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.campus
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String campus;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.major
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_student.poor_level
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String poorLevel;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.sex
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_student.class_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.nation
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.phone
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.email
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.qq
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.grade
     *
     * @mbg.generated Mon Oct 01 22:15:51 CST 2018
     */
    private String grade;
}
