mybatis:
  mapper-locations: classpath:mybatis/mapper/cn/sduonline/wings/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.sduonline.wings.model

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wings
    password: 0nlin@wings
    url: jdbc:mysql://localhost:3306/wings?useUnicode=true&character_set_server=utf8mb4&useSSL=false

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
