package cn.sduonline.wings.model;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_admin.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_admin.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_admin.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_admin.username
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_admin.password
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_admin.id
     *
     * @return the value of wings_admin.id
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_admin.id
     *
     * @param id the value for wings_admin.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_admin.gmt_create
     *
     * @return the value of wings_admin.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_admin.gmt_create
     *
     * @param gmtCreate the value for wings_admin.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_admin.gmt_modified
     *
     * @return the value of wings_admin.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_admin.gmt_modified
     *
     * @param gmtModified the value for wings_admin.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_admin.username
     *
     * @return the value of wings_admin.username
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_admin.username
     *
     * @param username the value for wings_admin.username
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_admin.password
     *
     * @return the value of wings_admin.password
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_admin.password
     *
     * @param password the value for wings_admin.password
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}