package cn.sduonline.wings.model;

public class Blacklist {
    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column wings_blacklist.id
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * wings_blacklist.student_no
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    private String studentNo;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wings_blacklist.id
     *
     * @return the value of wings_blacklist.id
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wings_blacklist.id
     *
     * @param id the value for wings_blacklist.id
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * wings_blacklist.student_no
     *
     * @return the value of wings_blacklist.student_no
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * wings_blacklist.student_no
     *
     * @param studentNo the value for wings_blacklist.student_no
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }
}