package cn.sduonline.wings.model;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.course_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.course_time
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.not_poor_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Integer notPoorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.total_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.grade_limit
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String gradeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.available_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Integer availableNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.deadline
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.course_location
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String courseLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_course.course_desc
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String courseDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.id
     *
     * @return the value of wings_course.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.id
     *
     * @param id the value for wings_course.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.gmt_create
     *
     * @return the value of wings_course.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.gmt_create
     *
     * @param gmtCreate the value for wings_course.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.gmt_modified
     *
     * @return the value of wings_course.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.gmt_modified
     *
     * @param gmtModified the value for wings_course.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.course_name
     *
     * @return the value of wings_course.course_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.course_name
     *
     * @param courseName the value for wings_course.course_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.course_time
     *
     * @return the value of wings_course.course_time
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.course_time
     *
     * @param courseTime the value for wings_course.course_time
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setCourseTime(String courseTime) {
        this.courseTime = courseTime == null ? null : courseTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.not_poor_num
     *
     * @return the value of wings_course.not_poor_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Integer getNotPoorNum() {
        return notPoorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.not_poor_num
     *
     * @param notPoorNum the value for wings_course.not_poor_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setNotPoorNum(Integer notPoorNum) {
        this.notPoorNum = notPoorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.total_num
     *
     * @return the value of wings_course.total_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.total_num
     *
     * @param totalNum the value for wings_course.total_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.grade_limit
     *
     * @return the value of wings_course.grade_limit
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getGradeLimit() {
        return gradeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.grade_limit
     *
     * @param gradeLimit the value for wings_course.grade_limit
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGradeLimit(String gradeLimit) {
        this.gradeLimit = gradeLimit == null ? null : gradeLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.available_num
     *
     * @return the value of wings_course.available_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Integer getAvailableNum() {
        return availableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.available_num
     *
     * @param availableNum the value for wings_course.available_num
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setAvailableNum(Integer availableNum) {
        this.availableNum = availableNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.deadline
     *
     * @return the value of wings_course.deadline
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.deadline
     *
     * @param deadline the value for wings_course.deadline
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.course_location
     *
     * @return the value of wings_course.course_location
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getCourseLocation() {
        return courseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.course_location
     *
     * @param courseLocation the value for wings_course.course_location
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setCourseLocation(String courseLocation) {
        this.courseLocation = courseLocation == null ? null : courseLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_course.course_desc
     *
     * @return the value of wings_course.course_desc
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getCourseDesc() {
        return courseDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_course.course_desc
     *
     * @param courseDesc the value for wings_course.course_desc
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setCourseDesc(String courseDesc) {
        this.courseDesc = courseDesc == null ? null : courseDesc.trim();
    }
}