package cn.sduonline.wings.model;

import java.util.Date;

public class Select {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_select.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_select.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_select.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_select.student_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_select.course_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_select.id
     *
     * @return the value of wings_select.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_select.id
     *
     * @param id the value for wings_select.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_select.gmt_create
     *
     * @return the value of wings_select.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_select.gmt_create
     *
     * @param gmtCreate the value for wings_select.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_select.gmt_modified
     *
     * @return the value of wings_select.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_select.gmt_modified
     *
     * @param gmtModified the value for wings_select.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_select.student_id
     *
     * @return the value of wings_select.student_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_select.student_id
     *
     * @param studentId the value for wings_select.student_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_select.course_id
     *
     * @return the value of wings_select.course_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_select.course_id
     *
     * @param courseId the value for wings_select.course_id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }
}