package cn.sduonline.wings.model;

import java.util.Date;

public class Setting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_setting.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_setting.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_setting.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_setting.setting_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String settingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wings_setting.setting_value
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    private String settingValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_setting.id
     *
     * @return the value of wings_setting.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_setting.id
     *
     * @param id the value for wings_setting.id
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_setting.gmt_create
     *
     * @return the value of wings_setting.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_setting.gmt_create
     *
     * @param gmtCreate the value for wings_setting.gmt_create
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_setting.gmt_modified
     *
     * @return the value of wings_setting.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_setting.gmt_modified
     *
     * @param gmtModified the value for wings_setting.gmt_modified
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_setting.setting_name
     *
     * @return the value of wings_setting.setting_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getSettingName() {
        return settingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_setting.setting_name
     *
     * @param settingName the value for wings_setting.setting_name
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setSettingName(String settingName) {
        this.settingName = settingName == null ? null : settingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wings_setting.setting_value
     *
     * @return the value of wings_setting.setting_value
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public String getSettingValue() {
        return settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wings_setting.setting_value
     *
     * @param settingValue the value for wings_setting.setting_value
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue == null ? null : settingValue.trim();
    }
}