package cn.sduonline.wings.model;

import java.util.Date;

import lombok.ToString;

@ToString
public class Student {
    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.id
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private Long id;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.gmt_create
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private Date gmtCreate;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.gmt_modified
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private Date gmtModified;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.student_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String studentNo;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.student_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String studentName;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.id_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String idNo;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.academy
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String academy;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.campus
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String campus;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.major
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String major;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.poor_level
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String poorLevel;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.sex
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String sex;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * wings_student.class_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String className;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.nation
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String nation;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.phone
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String phone;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.email
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String email;

    /**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.qq
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    private String qq;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wings_student.grade
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
	private String grade;

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.id
	 *
	 * @return the value of wings_student.id
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public Long getId() {
        return id;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.id
	 *
	 * @param id
	 *            the value for wings_student.id
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setId(Long id) {
        this.id = id;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.gmt_create
	 *
	 * @return the value of wings_student.gmt_create
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for wings_student.gmt_create
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.gmt_modified
	 *
	 * @return the value of wings_student.gmt_modified
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for wings_student.gmt_modified
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.student_no
	 *
	 * @return the value of wings_student.student_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getStudentNo() {
        return studentNo;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.student_no
	 *
	 * @param studentNo
	 *            the value for wings_student.student_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo == null ? null : studentNo.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.student_name
	 *
	 * @return the value of wings_student.student_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getStudentName() {
        return studentName;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.student_name
	 *
	 * @param studentName
	 *            the value for wings_student.student_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.id_no
	 *
	 * @return the value of wings_student.id_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getIdNo() {
        return idNo;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.id_no
	 *
	 * @param idNo
	 *            the value for wings_student.id_no
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.academy
	 *
	 * @return the value of wings_student.academy
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getAcademy() {
        return academy;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.academy
	 *
	 * @param academy
	 *            the value for wings_student.academy
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.campus
	 *
	 * @return the value of wings_student.campus
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getCampus() {
        return campus;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.campus
	 *
	 * @param campus
	 *            the value for wings_student.campus
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setCampus(String campus) {
        this.campus = campus == null ? null : campus.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.major
	 *
	 * @return the value of wings_student.major
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getMajor() {
        return major;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.major
	 *
	 * @param major
	 *            the value for wings_student.major
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.poor_level
	 *
	 * @return the value of wings_student.poor_level
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getPoorLevel() {
        return poorLevel;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.poor_level
	 *
	 * @param poorLevel
	 *            the value for wings_student.poor_level
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setPoorLevel(String poorLevel) {
        this.poorLevel = poorLevel == null ? null : poorLevel.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.sex
	 *
	 * @return the value of wings_student.sex
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getSex() {
        return sex;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.sex
	 *
	 * @param sex
	 *            the value for wings_student.sex
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.class_name
	 *
	 * @return the value of wings_student.class_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getClassName() {
        return className;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.class_name
	 *
	 * @param className
	 *            the value for wings_student.class_name
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.nation
	 *
	 * @return the value of wings_student.nation
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getNation() {
        return nation;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.nation
	 *
	 * @param nation
	 *            the value for wings_student.nation
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.phone
	 *
	 * @return the value of wings_student.phone
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getPhone() {
        return phone;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.phone
	 *
	 * @param phone
	 *            the value for wings_student.phone
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.email
	 *
	 * @return the value of wings_student.email
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getEmail() {
        return email;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.email
	 *
	 * @param email
	 *            the value for wings_student.email
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.qq
	 *
	 * @return the value of wings_student.qq
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public String getQq() {
        return qq;
    }

    /**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.qq
	 *
	 * @param qq
	 *            the value for wings_student.qq
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * wings_student.grade
	 *
	 * @return the value of wings_student.grade
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
	public String getGrade() {
		return grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * wings_student.grade
	 *
	 * @param grade
	 *            the value for wings_student.grade
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
	public void setGrade(String grade) {
		this.grade = grade == null ? null : grade.trim();
    }
}