package cn.sduonline.wings.dao.mapper;

import java.util.List;

import cn.sduonline.wings.model.Admin;
import cn.sduonline.wings.model.condition.AdminCondition;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    Admin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_admin
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKey(Admin record);

	List<Admin> selectByCondition(AdminCondition condition);
}