package cn.sduonline.wings.dao.mapper;

import cn.sduonline.wings.model.Blacklist;

public interface BlacklistMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    int insert(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    int insertSelective(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    Blacklist selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    int updateByPrimaryKeySelective(Blacklist record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table wings_blacklist
     *
     * @mbg.generated Wed Mar 20 10:50:09 CST 2019
     */
    int updateByPrimaryKey(Blacklist record);

    boolean existsByStuNo(String studentNo);
}