package cn.sduonline.wings.dao.mapper;

import java.util.List;

import cn.sduonline.wings.model.Course;
import cn.sduonline.wings.model.condition.CourseCondition;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    Course selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_course
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKey(Course record);

	List<Course> selectByCondition(CourseCondition condition);

	Course selectByPrimaryKeyForUpdate(Long id);

    int deleteAll();
}