package cn.sduonline.wings.dao.mapper;

import java.util.List;

import cn.sduonline.wings.model.Select;
import cn.sduonline.wings.model.condition.SelectCondition;
import cn.sduonline.wings.vo.SelectionVO;

public interface SelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insert(Select record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insertSelective(Select record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    Select selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeySelective(Select record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_select
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKey(Select record);

	List<Select> selectByCondition(SelectCondition condition);

	List<SelectionVO> selectJoinCourse(SelectCondition condition);

	int countByCondition(SelectCondition condition);
}