package cn.sduonline.wings.dao.mapper;

import cn.sduonline.wings.model.Setting;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    Setting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wings_setting
     *
     * @mbg.generated Sat Sep 29 20:10:15 CST 2018
     */
    int updateByPrimaryKey(Setting record);
}