package cn.sduonline.wings.dao.mapper;

import java.util.List;

import cn.sduonline.wings.model.Student;
import cn.sduonline.wings.model.condition.StudentCondition;

public interface StudentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    int deleteByPrimaryKey(Long id);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    int insert(Student record);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    int insertSelective(Student record);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    Student selectByPrimaryKey(Long id);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    int updateByPrimaryKeySelective(Student record);

    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wings_student
	 *
	 * @mbg.generated Mon Oct 01 22:15:51 CST 2018
	 */
    int updateByPrimaryKey(Student record);

	List<Student> selectByCondition(StudentCondition condition);

	int insertBatch(List<Student> list);

	List<Student> selectAll();

    int deleteAll();
}